### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by krinkere** [u39kun/ambari-vagrant#5]
My system
MacOS
VirtualBox 4.3.20
Vagrant 1.7.1

I followed steps out outlined in https://cwiki.apache.org/confluence/display/AMBARI/Quick+Start+Guide

and received following error during step 3 http://c6401.ambari.apache.org:8080/#/installer/step3

==========================
Creating target directory...
==========================

Command start time 2015-02-07 16:25:11

Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
SSH command execution finished
host=c6401.ambari.apache.org, exitcode=255
Command end time 2015-02-07 16:25:11

ERROR: Bootstrap of host c6401.ambari.apache.org fails because previous action finished with non-zero exit code (255)
ERROR MESSAGE: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

STDOUT: 
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

I also tried to add 

vagrant ALL=(ALL) NOPASSWD: ALL 

to visudo, but it did not work.

Any ideas?

**Comment by u39kun** [comment]
In Step3:
* Did you specify the correct private key file?
* What did you specify as the SSH username?

**Comment by krinkere** [comment]
Ummm sorry notification did not work for some reason, thank you for responding!

1. I specified ~/.vagrant.d/insecure_private_key
2. I put vagrant as a SSH username

**Comment by zenlc2000** [comment]
I'm having the same problem with the same error message, have followed the same steps, including the ~/.vagrant.d/insecure_private_key and vagrant user name.

Also, I'm running on a MacBook Pro OSX 10.10.2, using Boot2Docker and CentOS 6.5 as the guest OS and I chose the stable version of Ambari from http://public-repo-1.hortonworks.com/ambari/centos6/1.x/updates/1.7.0/ambari.repo.

One thing I notice, when I try to SSH from c6501 to c6502 or c6503, it **does** ask for a password, although doing a vagrant ssh c6501, etc. **does not.**

I read there is an Ambari bug with Python 2.7.9 and the workaround is to put PYTHON=2.6 in /var/lib/ambari-agent/ambari-env.sh. Unfortunately, I don't seem to have an ambari-agent directory at that location, which leads me to believe the ambari agent isn't downloaded, but that could happen after host registration, I'm not sure....

**Comment by u39kun** [comment]
Ok, the problem was the change in behavior with more recent versions of VirtualBox.
I was using 1.6.5, but I tried the latest (1.7.2) and I started having the same issues that you described.
This is due to https://github.com/mitchellh/vagrant/pull/4707.
I've updated Vagrantfile for various OS's, so you should not have this issue anymore.

**Comment by krinkere** [comment]
Gotcha. 

Thank you for looking into this! I will try it out tonight.

**Comment by zenlc2000** [comment]
Outstanding! Your timely response saved my project's grade :).
